wskh.Web/Areas/TimeAttendance/Controllers/SpecialDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeAttendance.Core;
using TimeAttendance.Model;
using TimeAttendance.Web.Helper;
using TimeAttendance.WebEssentials;
using TimeAttendance.WebEssentials.CommandPart;
using wskh.Core.Enumerator;
using wskh.Service;
using wskh.Web.Helper;
using wskh.WebEssentials.DataTablePart;
using wskh.WebEssentials.DateAndTime;

namespace wskh.Web.Areas.TimeAttendance.Controllers
{
    public class SpecialDayController : Controller
    {
        #region Propertices
        private ISpecialDayService _specialDayService;
        private IWorkProgramService _workProgramService;
        #endregion
        #region Ctor
        public SpecialDayController(ISpecialDayService specialDayService, IWorkProgramService workProgramService)
        {
            _specialDayService = specialDayService;
            _workProgramService = workProgramService;
        }
        #endregion
        #region Index
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.PanelName = "rulesandprograms";
            ViewBag.MenuName = "specialday";
            return View();
        }
        #endregion
        #region List
        [HttpGet]
        public ActionResult ListIndex()
        {
            return PartialView("_List");
        }
        [HttpGet]
        public JsonResult List(DataTableRequest request, [ModelBinder(typeof(DataTableModelBinder))]DataTableRequestFilter filter)
        {
            #region Grid configuration
            if (request.length == -1)
            {
                request.length = int.MaxValue;
            }
            var modelItem = new DataTableResponse<SpecialDayModel>();
            modelItem.draw = request.draw;
            var data = _specialDayService.FilterData(request.start, request.length, filter.Search);
            modelItem.recordsTotal = _specialDayService.Count(filter.Search);
            modelItem.recordsFiltered = modelItem.recordsTotal;
            #endregion
            #region Prepare model
            var add = request.start;
            data.ForEach(x =>
            {
                var model = new SpecialDayModel();
                model.Index = ++add;
                model.Id = x.Id;
                model.Title = x.Title;
                model.DelayEnterance = $"{x.DelayEnterance} <br/> {x.DelayExit}";
                model.EndDate = x.EndDate != null ? DateTimeHelper.TopersianDate(x.EndDate.GetValueOrDefault()) : "-";
                model.StartDate = DateTimeHelper.TopersianDate(x.StartDate);
                model.WorkProgramString = x.SpecialDayGrouping.Title;

                model.StartDate = $"{model.StartDate}";

                model.SpecialDayGroupingString = x.SpecialDayGroupingId == null ? "-" : x.SpecialDayGrouping.Title;
                //model.WorkProgramString = x.WorkProgramId != null && x.Type == Core.Enumerator.SpecialDayType.SpecialDuration ? x.WorkProgram.Title : "-";
                switch (x.Type)
                {
                    case Core.Enumerator.SpecialDayType.Holiday:
                        model.TypeString = "تعطیلات";
                        break;
                    case Core.Enumerator.SpecialDayType.SpecialDay:
                        model.TypeString = "روز خاص";
                        break;
                    case Core.Enumerator.SpecialDayType.SpecialDuration:
                        model.TypeString = "ایام خاص";
                        break;
                    default:
                        model.TypeString = "-";
                        break;
                }

                modelItem.data.Add(model);
            });
            #endregion

            return Json(modelItem, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Add or Update
        [HttpGet]
        public ActionResult AddOrUpdate(int id = 0)
        {
            SpecialDayModel model = new SpecialDayModel();
            return PartialView("_AddOrUpdate", model);
        }
        [HttpPost]
        public ActionResult AddOrUpdate(SpecialDayModel model)
        {
            JsonModel jsonModel = new JsonModel();
            if (ModelState.IsValid)
            {
                try
                {
                    SpecialDay entity = new SpecialDay();
                    if (model.Id.GetValueOrDefault() > 0)
                    {
                    }
                    else
                    {
                        var entityList = _specialDayService.GetList;
                        if (entityList != null && entityList.Count() > 0)
                        {
                            entityList = entityList.Where(x => x.SpecialDayGroupingId == model.SpecialDayGroupingId).ToList();
                            if (model.TypeId == 1 && entityList != null && entityList.Count() > 0)
                            {
                                entityList = CheckListOne(model, entityList);
                                if (entityList.Count > 0)
                                {
                                    model = PrepareCreate(model, jsonModel, entity);
                                }
                                else if (model.TypeId == 2 && entityList != null && entityList.Count() > 0)
                                {
                                    jsonModel.State = "15";
                                    jsonModel.Message = "تاریخ تکراری میباشد";
                                }
                            }
                            else
                            {
                                entityList = CheckListTwo(model, entityList);
                                if (entityList.Count >= 0)
                                {
                                    model = PrepareCreate(model, jsonModel, entity);
                                }
                                else
                                {
                                    jsonModel.State = "15";
                                    jsonModel.Message = "بازه تاریخی تکراری میباشد";
                                }
                            }

                        }
                        else
                        {
                            model = PrepareCreate(model, jsonModel, entity);
                        }

                    }

                }
                catch (Exception e)
                {
                    jsonModel.Exception();
                }
            }
            jsonModel.Html = HtmlToJsonHelper.RenderPartialView(this, "_AddOrUpdate", model);
            return Json(jsonModel);
        }

        private static List<SpecialDay> CheckListTwo(SpecialDayModel model, List<SpecialDay> entityList)
        {
            entityList = entityList.Where(x => x.Type == SpecialDayType.Holiday).ToList();
            if (entityList != null && entityList.Count() > 0)
                entityList = entityList
                    .Where(x => 
                    (x.StartDate.Date >= model.StartDate.ToGeoDate().GetValueOrDefault() && x.EndDate.GetValueOrDefault().Date <= model.StartDate.ToGeoDate().GetValueOrDefault()) ||
                     (x.StartDate.Date >= model.EndDate.ToGeoDate().GetValueOrDefault() && x.EndDate.GetValueOrDefault().Date <= model.EndDate.ToGeoDate().GetValueOrDefault())
                     ).ToList();
            return entityList;
        }

        private static List<SpecialDay> CheckListOne(SpecialDayModel model, List<SpecialDay> entityList)
        {
            entityList = entityList.Where(x => x.Type == SpecialDayType.Holiday).ToList();
            if (entityList != null && entityList.Count() > 0)
                entityList = entityList.Where(x => x.StartDate.Date == model.StartDate.ToGeoDate().GetValueOrDefault()).ToList();
            return entityList;
        }

        private SpecialDayModel PrepareCreate(SpecialDayModel model, JsonModel jsonModel, SpecialDay entity)
        {
            entity.Id = entity.Id;
            entity.EndDate = entity.EndDate;
            entity.StartDate = DateTimeHelper.ToGeoDate(model.StartDate).GetValueOrDefault();
            entity.Title = model.Title;
            entity.DelayEnterance = model.DelayEnterance;
            entity.DelayExit = model.DelayExit;
            entity.SpecialDayGroupingId = model.SpecialDayGroupingId;
            entity.Type = (SpecialDayType)model.TypeId;
            _specialDayService.Create(entity);


            CommandHelper.Create(CommandCategory.SpecialDayChange, false, $"ایجاد تعطیلی/روزخاص در تقویم با نام : {entity.Title}", 0, UserHelper.CurrentUser(), entity.Id);

            //CalendarHistoryHelper.UpdateBySpecialDay(entity.Id);

            model = new SpecialDayModel();
            jsonModel.Success();
            return model;
        }
        #endregion
        #region Delete
        public ActionResult Delete(int id = 0)
        {
            bool result = false;
            try
            {
                SpecialDay entity = _specialDayService.FindById(id);
                _specialDayService.Delete(entity);
                result = true;
            }
            catch (Exception e)
            {
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Description
        public ActionResult Description()
        {
            return PartialView("_Description");
        }
        #endregion
    }
}

wskh.Web/Areas/TimeAttendance/Controllers/SpecialDayGroupingController.cs
using AutoMapper;
using System;
using System.Web.Mvc;
using TimeAttendance.Core;
using TimeAttendance.Model;
using wskh.Core;
using wskh.Model;
using wskh.Service;
using wskh.Web.Helper;
using wskh.WebEssentials.DataTablePart;

namespace wskh.Web.Areas.TimeAttendance.Controllers
{
    [Authorize]
    public class SpecialDayGroupingController : Controller
    {
        #region Propertices
        private readonly ISpecialDayGroupingService _SpecialDayGroupingService;
        #endregion
        #region Ctor
        public SpecialDayGroupingController(ISpecialDayGroupingService SpecialDayGroupingService)
        {
            _SpecialDayGroupingService = SpecialDayGroupingService;
        }
        #endregion
        #region Index
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.MenuName = "specialdaygrouping";

            return View();
        }
        #endregion
        #region List
        [HttpGet]
        public ActionResult ListIndex()
        {
            return PartialView("_List");
        }
        [HttpGet]
        public JsonResult List(DataTableRequest request, [ModelBinder(typeof(DataTableModelBinder))]DataTableRequestFilter filter)
        {
            #region Grid configuration
            if (request.length == -1)
            {
                request.length = int.MaxValue;
            }
            var modelItem = new DataTableResponse<SpecialDayGroupingModel>();
            modelItem.draw = request.draw;
            var data = _SpecialDayGroupingService.FilterData(request.start, request.length, filter.Search);
            modelItem.recordsTotal = _SpecialDayGroupingService.Count(filter.Search);
            modelItem.recordsFiltered = modelItem.recordsTotal;
            #endregion
            #region Prepare model
            var add = request.start;
            data.ForEach(x =>
            {
                var model = new SpecialDayGroupingModel();
                model.Index = ++add;
                model.Id = x.Id;
                model.Title = x.Title;

                modelItem.data.Add(model);
            });
            #endregion

            return Json(modelItem, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Add or update
        [HttpGet]
        public ActionResult AddOrUpdate(int id = 0)
        {
            SpecialDayGroupingModel model = new SpecialDayGroupingModel();
            if (id > 0)
            {
                SpecialDayGrouping entity = _SpecialDayGroupingService.FindById(id);
                model = Mapper.Map<SpecialDayGrouping, SpecialDayGroupingModel>(entity);
            }
            return PartialView("_AddOrUpdate", model);
        }
        [HttpPost]
        public ActionResult AddOrUpdate(SpecialDayGroupingModel model)
        {
            JsonModel jsonModel = new JsonModel();
            if (ModelState.IsValid)
            {
                try
                {
                    SpecialDayGrouping entity = new SpecialDayGrouping();
                    if (model.Id.GetValueOrDefault() > 0)
                    {
                        entity = new SpecialDayGrouping();
                        entity = Mapper.Map<SpecialDayGroupingModel, SpecialDayGrouping>(model);
                        _SpecialDayGroupingService.Update(entity);
                    }
                    else
                    {
                        entity = Mapper.Map<SpecialDayGroupingModel, SpecialDayGrouping>(model);
                        _SpecialDayGroupingService.Create(entity);
                    }
                    model = new SpecialDayGroupingModel();
                    jsonModel.Success();
                }
                catch (Exception e)
                {
                    jsonModel.Exception();
                }
            }
            jsonModel.Html = HtmlToJsonHelper.RenderPartialView(this, "_AddOrUpdate", model);
            return Json(jsonModel);
        }
        #endregion
        #region Delete
        public ActionResult Delete(int id = 0)
        {
            bool result = false;
            try
            {
                SpecialDayGrouping entity = _SpecialDayGroupingService.FindById(id);
                _SpecialDayGroupingService.Delete(entity);
                result = true;
            }
            catch (Exception e)
            {
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Description
        public ActionResult Description()
        {
            return PartialView("_Description");
        }
        #endregion
    }
}

wskh.Web/Areas/TimeAttendance/Views/SpecialDayGrouping/Index.cshtml
@{
    ViewBag.Title = "قوانین و برنامه ها | گروهبندی تعطیلات و ایام خاص";
    Layout = "~/Areas/TimeAttendance/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_AccessControll")

<link href="~/wwwroot/componenets/datatableajax/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/wwwroot/componenets/global/global.css" rel="stylesheet" />



<div class="panel-group">
    <div class="col-12">

        <div class="panel panel-default">
            <div class="panel-heading panel-headingDanger" onclick="ShowPanel('Grouping')">
                <h4 class="panel-title">
                    <a data-toggle="collapse">
                        گروهبندی تعطیلات و ایام خاص
                    </a>
                </h4>
                <a class="btn btn-warning pull-left custome-btn-left" href="/TimeAttendance/PDF/PrintSpecialDayGrouping" target="_blank">چاپ</a>
            </div>
            <div id="Grouping" class="panel-collapse collapse panel-bodyDanger" style="display:block;">
                <div class="col-12">

                    <div class="row">

                        <div class="col-md-4 col-sm-12">
                            <div class="card card-topline-red">
                                <div class="card-head">
                                    <header>ثبت / ویرایش</header>
                                    <i class="fa fa-helper poiner information" onclick="getDescription('/TimeAttendance/SpecialDayGrouping/Description')"></i>
                                </div>
                                <div class="card-body ">
                                    @using (Ajax.BeginForm("AddOrUpdate", "SpecialDayGrouping", new AjaxOptions { HttpMethod = "Post", OnSuccess = "Success" }))
                                    {
                                        <div id="AddOrUpdate-Part">
                                            @Html.Action("AddOrUpdate", "SpecialDayGrouping", new { id = 0 })
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>


                        <div class="col-md-8 col-sm-12">
                            <div class="card card-topline-red">
                                <div class="card-head">
                                    <header>گزارش</header>
                                </div>
                                <div class="card-body " id="Grid-Part">
                                    @Html.Action("ListIndex", "SpecialDayGrouping")
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>


    </div>

    <div class="col-12">

        <div class="panel panel-default">
            <div class="panel-heading panel-headingDanger" onclick="ShowPanel('Hoidays')">
                <h4 class="panel-title">
                    <a data-toggle="collapse">
                        تعطیلات و ایام خاص
                    </a>
                </h4>
                <a class="btn btn-warning pull-left custome-btn-left" href="/TimeAttendance/PDF/PrintSpecialDay" target="_blank">چاپ</a>
            </div>
            <div id="Hoidays" class="panel-collapse collapse panel-bodyDanger">
                <div class="col-12">



                    <div class="row">

                        <div class="col-md-4 col-sm-12">
                            <div class="card card-topline-red">
                                <div class="card-head">
                                    <header>ثبت / ویرایش</header>
                                    <i class="fa fa-helper poiner information" onclick="getDescription('/TimeAttendance/SpecialDay/Description')"></i>
                                </div>
                                <div class="card-body ">
                                    @using (Ajax.BeginForm("AddOrUpdate", "SpecialDay", new AjaxOptions { HttpMethod = "Post", OnSuccess = "Success2" }))
                                    {
                                        <div id="AddOrUpdate-Part2">
                                            @Html.Action("AddOrUpdate", "SpecialDay", new { id = 0 })
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>


                        <div class="col-md-8 col-sm-12">
                            <div class="card card-topline-red">
                                <div class="card-head">
                                    <header>گزارش</header>
                                </div>
                                <div class="card-body " id="Grid-Part2">
                                    @Html.Action("ListIndex", "SpecialDay")
                                </div>
                            </div>
                        </div>

                    </div>



                </div>
            </div>
        </div>


    </div>
</div>









@section scripts
{
    <script src="~/wwwroot/controllersGrid/specialdaygrouping.js"></script>
    <script src="~/wwwroot/componenets/unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/wwwroot/componenets/global/global.js"></script>
    <script src="~/wwwroot/controllersGrid/specialday.js"></script>

    <script>
        function Success(data) {  
            $("#AddOrUpdate-Part").html(data.Html);
            blink("AddOrUpdate-Part");
            if (data.State == "0") { 
                Message(data.State, data.Message);
            }
            GridReload("Grid");
            if (data.State == "0") { 
                GetEmptyView("/TimeAttendance/SpecialDayGrouping/AddOrUpdate", "AddOrUpdate-Part");
                GetCreate();
            }
        }

        function Success2(data) {
            $("#AddOrUpdate-Part2").html(data.Html);
            blink("AddOrUpdate-Part2");
            if (data.State == "0") { 
                Message(0, data.Message);
            }
            if (data.State == "1") {
                Message(1, data.Message);
            }
            if (data.State == "15") {
                Message(1, data.Message);
            }
            GridReload("Grid2");
            if (data.State == "0") { 
                GetEmptyView("/TimeAttendance/SpecialDay/AddOrUpdate", "AddOrUpdate-Part2");
            }
        }

        function GetCreate() {
            GridReload("Grid");
            GridReload("Grid2");
            GetEmptyView("/TimeAttendance/SpecialDay/AddOrUpdate", "AddOrUpdate-Part2");
        }
    </script>
}


<script src="~/wwwroot/componenets/global/global.js"></script>
<script>
    function ShowPanel($id) {
        $("#" + $id).slideToggle();
    }
</script>

wskh.Web/Areas/TimeAttendance/Views/SpecialDayGrouping/_AddOrUpdate.cshtml
@model TimeAttendance.Model.SpecialDayGroupingModel
@{
    Layout = null;
}

@Html.AntiForgeryToken()
@Html.HiddenFor(x => x.Id)

<div class="form-group w100">
    @Html.LabelFor(x => x.Title, new { @class = "pull-right" })<label class="required">*</label>
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control", MaxLength = "50" })
    @Html.ValidationMessageFor(x => x.Title, null, new { @class = "validation" })
</div>


<button type="submit" onclick="AddLoading()" class="btn btn-success btn-sm pull-left">ثبت / ویرایش</button>

wskh.Web/Areas/TimeAttendance/Views/SpecialDayGrouping/_Description.cshtml
@{
    Layout = null;
}


<div class="col-12">

    <label class="lblTitle lbl">مقطع تحصیلی</label>
    <label class="lblDescription lbl">
        دراین فرم به تعریف گروهبندی تعطیلات و روزهای خاص پرداخته میشود. اطلاعات این فرم در بخش های دیگر نرم افزار مورد استفاده قرار میگیرد
    </label>
    <label class="lblExample lbl">
        بطور مثال : "تعطیلات واحد اداری سال 1398" و ... میباشند
    </label>

    <hr class="lblHr" />

</div>
<div class="col-12">

    <label class="lblTitle lbl">عنوان</label>
    <label class="lblDescription lbl">
        تعریف عنوان گرو تعطیلی و روز خاص
        <br />
        * حداکثر طول 50 کاراکتر میباشد
    </label>
    <label class="lblExample lbl">
        بطور مثال : "تعطیلات واحد اداری سال 1398" و ... میباشند
    </label>


</div>

wskh.Web/Areas/TimeAttendance/Views/SpecialDayGrouping/_List.cshtml
@{
    Layout = null;
}



<table id="Grid" class="table  table-striped table-condensed table-bordered no-margin" style="width:100% !important;">
    <thead>
        <tr>
            <th>ردیف</th>
            <th>عنوان</th>
            <th>عملیات</th>
        </tr>
    </thead>
</table>