wskh.Web/Areas/TimeAttendance/Controllers/OrganizationBranchController.cs
using AutoMapper;
using System;
using System.Web.Mvc;
using wskh.Core;
using wskh.Model;
using wskh.Service;
using wskh.Web.Helper;
using wskh.WebEssentials.DataTablePart;

namespace wskh.Web.Areas.TimeAttendance.Controllers
{
    [Authorize]
    public class OrganizationBranchController : Controller
    {
        #region Propertices
        private readonly IOrganizationBranchService _OrganizationBranchService;
        #endregion
        #region Ctor
        public OrganizationBranchController(IOrganizationBranchService OrganizationBranchService)
        {
            _OrganizationBranchService = OrganizationBranchService;
        }
        #endregion
        #region Index
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.MenuName = "organizationbranch";
            return View();
        }
        #endregion
        #region List
        [HttpGet]
        public ActionResult ListIndex()
        {
            return PartialView("_List");
        }
        [HttpGet]
        public JsonResult List(DataTableRequest request, [ModelBinder(typeof(DataTableModelBinder))]DataTableRequestFilter filter)
        {
            #region Grid configuration
            if (request.length == -1)
            {
                request.length = int.MaxValue;
            }
            var modelItem = new DataTableResponse<OrganizationBranchModel>();
            modelItem.draw = request.draw;
            var data = _OrganizationBranchService.FilterData(request.start, request.length, filter.Search);
            modelItem.recordsTotal = _OrganizationBranchService.Count(filter.Search);
            modelItem.recordsFiltered = modelItem.recordsTotal;
            #endregion
            #region Prepare model
            var add = request.start;
            data.ForEach(x =>
            {
                var model = new OrganizationBranchModel();
                model.Index = ++add;
                model.Id = x.Id;
                model.Title = x.Title;

                modelItem.data.Add(model);
            });
            #endregion

            return Json(modelItem, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Add or update
        [HttpGet]
        public ActionResult AddOrUpdate(int id = 0)
        {
            OrganizationBranchModel model = new OrganizationBranchModel();
            if (id > 0)
            {
                OrganizationBranch entity = _OrganizationBranchService.FindById(id);
                model = Mapper.Map<OrganizationBranch, OrganizationBranchModel>(entity);
            }
            return PartialView("_AddOrUpdate", model);
        }
        [HttpPost]
        public ActionResult AddOrUpdate(OrganizationBranchModel model)
        {
            JsonModel jsonModel = new JsonModel();
            if (ModelState.IsValid)
            {
                try
                {
                    OrganizationBranch entity = new OrganizationBranch();
                    if (model.Id.GetValueOrDefault() > 0)
                    {
                        entity = new OrganizationBranch();
                        entity = Mapper.Map<OrganizationBranchModel, OrganizationBranch>(model);
                        _OrganizationBranchService.Update(entity);
                    }
                    else
                    {
                        entity = Mapper.Map<OrganizationBranchModel, OrganizationBranch>(model);
                        _OrganizationBranchService.Create(entity);
                    }
                    model = new OrganizationBranchModel();
                    jsonModel.Success();
                }
                catch (Exception e)
                {
                    jsonModel.Exception();
                }
            }
            jsonModel.Html = HtmlToJsonHelper.RenderPartialView(this, "_AddOrUpdate", model);
            return Json(jsonModel);
        }
        #endregion
        #region Delete
        public ActionResult Delete(int id = 0)
        {
            int result = 0;
            try
            {
                OrganizationBranch entity = _OrganizationBranchService.FindById(id);
                if (entity.Users != null && entity.Users.Count > 0)
                {
                    result = -1;
                }
                else
                {
                    _OrganizationBranchService.Delete(entity);
                    result = 1;
                }
            }
            catch (Exception e)
            {
                result = -2;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Description
        public ActionResult Description()
        {
            return PartialView("_Description");
        }
        #endregion
    }
}

wskh.Web/Areas/TimeAttendance/Views/OrganizationBranch/Index.cshtml
@{
    ViewBag.Title = "اطلاعات پایه | شعبات سازمان";
    Layout = "~/Areas/TimeAttendance/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_AccessControll")

<link href="~/wwwroot/componenets/datatableajax/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/wwwroot/componenets/global/global.css" rel="stylesheet" />


<div class="row">

    <div class="col-md-4 col-sm-12">
        <div class="card card-topline-red">
            <div class="card-head">
                <header>ثبت / ویرایش</header>
                <i class="fa fa-helper poiner information" onclick="getDescription('/TimeAttendance/OrganizationBranch/Description')"></i>
            </div>
            <div class="card-body ">
                @using (Ajax.BeginForm("AddOrUpdate", "OrganizationBranch", new AjaxOptions { HttpMethod = "Post", OnSuccess = "Success" }))
                {
                    <div id="AddOrUpdate-Part">
                        @Html.Action("AddOrUpdate", "OrganizationBranch", new { id = 0 })
                    </div>
                }
            </div>
        </div>
    </div>


    <div class="col-md-8 col-sm-12">
        <div class="card card-topline-red">
            <div class="card-head">
                <header>گزارش</header>
            </div>
            <div class="card-body " id="Grid-Part">
                <a class="btn btn-warning" href="/TimeAttendance/PDF/PrintOrganizationBranch" target="_blank">چاپ</a>
                @Html.Action("ListIndex", "OrganizationBranch")
            </div>
        </div>
    </div>

</div>




@section scripts
{
    <script src="~/wwwroot/controllersGrid/organizationbranch.js"></script>
    <script src="~/wwwroot/componenets/unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/wwwroot/componenets/global/global.js"></script>
    <script>
         function Success(data) {  
            $("#AddOrUpdate-Part").html(data.Html);
            blink("AddOrUpdate-Part");
            if (data.State == "0") { 
                Message(data.State, data.Message);
            }
            GridReload("Grid");
            if (data.State == "0") { 
                GetEmptyView("/TimeAttendance/OrganizationBranch/AddOrUpdate", "AddOrUpdate-Part");
            }
        }
    </script>
}

wskh.Web/Areas/TimeAttendance/Views/OrganizationBranch/_AddOrUpdate.cshtml
@model wskh.Model.OrganizationBranchModel
@{
    Layout = null;
}

@Html.AntiForgeryToken()
@Html.HiddenFor(x => x.Id)

<div class="form-group w100">
    @Html.LabelFor(x => x.Title, new { @class = "pull-right" })<label class="required">*</label>
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control w100", MaxLength = "75" })
    @Html.ValidationMessageFor(x => x.Title, null, new { @class = "validation" })
</div>


<button type="submit" onclick="AddLoading()" class="btn btn-success btn-sm pull-left">ثبت / ویرایش</button>

wskh.Web/Areas/TimeAttendance/Views/OrganizationBranch/_Description.cshtml
@{
    Layout = null;
}



<div class="col-12">

    <label class="lblTitle lbl">شعبات سازمان</label>
    <label class="lblDescription lbl">
        دراین فرم به تعریف شعبات سازمان پرداخته میشود و اطلاعات این فرم در بخش های دیگر مورد استفاده قرار میگیرند
    </label>
    <label class="lblExample lbl">
        بطور مثال : "شعبه اداری" ، "واحد برنامه نویسی" و ... میباشند
    </label>

    <hr class="lblHr" />

</div>
<div class="col-12">

    <label class="lblTitle lbl">عنوان شعبه سازمان</label>
    <label class="lblDescription lbl">
        عنوان شعبه در این بخش درج میشود
        <br />
        * حداکثر طول 75 کاراکتر میباشد
    </label>
    <label class="lblExample lbl">
        بطور مثال : "شعبه اداری" ، "واحد برنامه نویسی" و ... میباشند
    </label>


</div>

wskh.Web/Areas/TimeAttendance/Views/OrganizationBranch/_List.cshtml
@{
    Layout = null;
}



<table id="Grid" class="table  table-striped table-condensed table-bordered no-margin" style="width:100% !important;">
    <thead>
        <tr>
            <th>ردیف</th>
            <th>عنوان سمت سازمانی</th>
            <th>عملیات</th>
        </tr>
    </thead>
</table>