wskh.Web/Areas/TimeAttendance/Controllers/AbsenceReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeAttendance.Core;
using TimeAttendance.Model;
using TimeAttendance.Web.Helper;
using TimeAttendance.WebEssentials.DateAndTime;
using TimeAttendance.WebEssentials.OtherHelper;
using TimeAttendance.WebEssentials.RequestPart;
using TimeAttendance.WebEssentials.StringAndNumber;
using wskh.Core;
using wskh.Core.Enumerator;
using wskh.Service;
using wskh.Web.Helper;
using wskh.WebEssentials.DataTablePart;
using wskh.WebEssentials.DateAndTime;

namespace wskh.Web.Areas.TimeAttendance.Controllers
{
    public class AbsenceReportController : Controller
    {
        #region Propertices
        private IAnalyzedReportService _analyzedReportService  { get; set; }
        private IUserService _userService { get; set; }
        #endregion


        #region Ctor

        public AbsenceReportController(IAnalyzedReportService analyzedReportService, IUserService userService)
        {
            _analyzedReportService = analyzedReportService;
            _userService = userService;
        }

        #endregion


        #region Index
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.MenuName = $"absenceeport";
            return View();
        }
        #endregion


        #region Search
        [HttpGet]
        public ActionResult Search()
        {
            AnalyzedReportModel model = new AnalyzedReportModel();
            return PartialView("_Search", model);
        }
        #endregion


        #region List
        [HttpGet]
        public ActionResult ListIndex(int groupId = 0, string userId = null, string stDate = null, string edDate = null, int analyzedReportState = 0)
        {
            List<AnalyzedReportListModel> enttityList = new List<AnalyzedReportListModel>();

            var userList = _userService.List().Where(x => x.UserGroupId == groupId).ToList();


            try
            {

                if (userList != null)
                {
                    foreach (var user in userList)
                    {
                        var list = new List<AnalyzedReport>();

                        var geoSTDate = !string.IsNullOrEmpty(stDate) ? DateTimeHelper.ToGeoDate(stDate) : DateTime.Now;
                        var geoEDDate = !string.IsNullOrEmpty(edDate) ? DateTimeHelper.ToGeoDate(edDate) : DateTime.Now;

                        list = _analyzedReportService.List(user.Id, geoSTDate.GetValueOrDefault(), geoEDDate.GetValueOrDefault());


                        if (list != null && list.Count() > 0)
                            list = list.Where(x =>
                                                    x.State == AnalyzedReportState.Absence_NoTransaction ||
                                                    x.State == AnalyzedReportState.Holiday_Absence_NoTransaction ||
                                                    x.State == AnalyzedReportState.Absence_Systemic ||
                                                    x.State == AnalyzedReportState.Holiday_Absence_Systemic ||
                                                    x.State == AnalyzedReportState.FractionTrade ||
                                                    x.State == AnalyzedReportState.HolidayFraction)
                                       .ToList();

                        if (list != null && list.Count() > 0)
                        {
                            switch (analyzedReportState)
                            {
                                case 1:
                                    list = list.Where(x => x.State == AnalyzedReportState.Absence_NoTransaction || x.State == AnalyzedReportState.Holiday_Absence_NoTransaction).ToList();
                                    break;
                                case 2:
                                    list = list.Where(x => x.State == AnalyzedReportState.Absence_Systemic || x.State == AnalyzedReportState.Holiday_Absence_Systemic).ToList();
                                    break;
                                case 3:
                                    list = list.Where(x => x.State == AnalyzedReportState.FractionTrade || x.State == AnalyzedReportState.HolidayFraction).ToList();
                                    break;
                                default:
                                    break;
                            }

                            list = list.OrderBy(x => x.Date.Date).ToList();
                        }

                        enttityList.Add(new AnalyzedReportListModel() {
                            StartDate = stDate,
                            EndDate = edDate,
                            UserGroup = user.UserGroup.Title,
                            UserInformattion = $"{user.FirstName} {user.Lastname}",
                            Reports = list
                        });
                    }
                }
              
            }
            catch (Exception e)
            {
                enttityList = new List<AnalyzedReportListModel>();
            }


            return PartialView("_List", enttityList);
        }
        #endregion


        #region PrepareDrop
        [HttpGet]
        public ActionResult GetUserDrop(int userGroupId = 0)
        {
            List<DropDownModel> modelList = new List<DropDownModel>();
            var userList = _userService.GetList.Where(x => x.UserGroupId == userGroupId).ToList();
            if (userList != null && userList.Count() > 0)
            {
                foreach (var user in userList)
                {
                    DropDownModel model = new DropDownModel()
                    {
                        Value = user.Id,
                        Text = $"{user.FirstName} {user.Lastname}"
                    };
                    modelList.Add(model);
                }
            }
            else
            {
                foreach (var user in userList)
                {
                    DropDownModel model = new DropDownModel()
                    {
                        Value = "0",
                        Text = $"کاربری در این گروه وجود ندارد"
                    };
                    modelList.Add(model);
                }
            }
            return PartialView("_GetUserDrop", modelList);
        }
        #endregion


        #region GetDrop
        public ActionResult GetDrop(int usergroupId = 0)
        {
            List<DropDownModel> modelList = new List<DropDownModel>();
            modelList.Add(new DropDownModel() { Value = "0", Text = "تمامی پرسنل" });

            if (usergroupId > 0)
            {
                var userList = _userService.GetList;
                if (!ListHelper.IsListNull(userList))
                {
                    userList = userList.Where(x => x.UserGroupId == usergroupId).ToList();

                    foreach (var user in userList)
                    {
                        modelList.Add(new DropDownModel() { Value = user.Id, Text = $"{user.FirstName} {user.Lastname}" });
                    }
                }
            }
            return View("_GetDrop", modelList);
        }
        #endregion
    }
}

wskh.Web/Areas/TimeAttendance/Views/AbsenceReport/Index.cshtml
@{
    ViewBag.Title = "گزارشات | گزارش خام تردد";
    Layout = "~/Areas/TimeAttendance/Views/Shared/_Layout.cshtml";
}

<link href="~/wwwroot/componenets/global/global.css" rel="stylesheet" />

<style>
    .panel-heading-gray {
        background: #ffdcd8;
    }
</style>



<div class="row">
    <div class="col-12">
        <div class="card card-topline-red">
            <div class="card-head">
                <header>
                    جستجو
                </header>
            </div>
            <div class="card-body " id="Search-Part">
                @Html.Action("Search", "AbsenceReport")
            </div>
        </div>
    </div>
</div>

<div class="row" id="HiddenPart">
    <div class="col-12">
        <div class="card card-topline-red">
            <div class="card-head">
                <header>گزارش</header>
            </div>
            <div class="card-body" id="Grid-Part">

            </div>
        </div>
    </div>
</div>




@section scripts
{
    <script src="~/wwwroot/componenets/global/global.js"></script>
    @*<script>
            $(document).ready(function () {
                $("#UserGroupId").select2();
                $("#UserId").select2();
            });
        </script>*@
    <script>
        function Search() {
            AddLoading();

            var $groupId = $("#UserGroupId").val();
            var $userId = $("#UserId").val();
            var $stDate = $("#StartDatePersian").val();
            var $edDate = $("#EndDatePersian").val();
            var $analyzedReportState = $("#TypeId").val();


            if ($groupId <= 0 ||
                $userId.length <= 0 ||
                $stDate.length <= 0 ||
                $stDate.length <= 0) {
                ReomveLoading();
                Message(1, "کلیه فیلدها را تکمیل نمایید");
            }
            else {
                $.ajax({
                    url: "/TimeAttendance/StimulReport/AbsenceNoLayoutIndex",
                    data: {
                        groupId: $groupId,
                        userId: $userId,
                        stDate: $stDate,
                        edDate: $edDate,
                        analyzedReportState: $analyzedReportState,
                    },
                    type: 'Get',
                    dataType: "html",
                    success: function (data) {
                        $("#Grid-Part").html(data);
                        ReomveLoading();
                    }
                });
            }
        }

        function SelectUsers() {
            $.ajax({
                url: "/TimeAttendance/AnalyzedReport/GetDrop?usergroupId=" + $("#UserGroupId").val(),
                type: 'Get',
                dataType: "html",
                success: function (data) {
                    $("#UserId").html(data);
                }
            });
        }
    </script>


    <script>
        function ShowMore(id) {
            var $id = id;
            $.ajax({
                url: "/TimeAttendance/AnalyzedReport/Detail?id=" + $id,
                type: 'Get',
                dataType: "html",
                success: function (data) {
                    bootbox.dialog({
                        message: data
                    });
                }
            });
        }
    </script>

    <script>
        function PrintPDF() {
            var $userGroupId = $("#UserGroupId").val();
            var $userId = $("#UserId").val();
            var $startDate = $("#StartDate").val();
            var $endDate = $("#EndDate").val();
            var $tradeTypeId = $("#TradeTypeId").val();


            var $groupId = $("#UserGroupId").val();
            var $userId = $("#UserId").val();
            var $stDate = $("#StartDatePersian").val();
            var $edDate = $("#EndDatePersian").val();
            var $analyzedReportState = $("#TypeId").val();

            if ($groupId <= 0 ||
                $userId.length <= 0 ||
                $stDate.length <= 0 ||
                $stDate.length <= 0) {
                ReomveLoading();
                Message(1, "کلیه فیلدها را تکمیل نمایید");
            }
            else {
                var url = "/TimeAttendance/StimulReport/AbsenceReportIndex?groupId=" + $groupId + "&userId=" + $userId + "&stDate=" + $stDate + "&edDate=" + $edDate + "&analyzedReportState=" + $analyzedReportState;
                window.open(url, '_blank');
            }
        }
    </script>
}

wskh.Web/Areas/TimeAttendance/Views/AbsenceReport/_GetDrop.cshtml
@model List<TimeAttendance.Model.DropDownModel>

@foreach (var item in Model)
{
    <option value="@(item.Value)">
        @item.Text
    </option>
}

wskh.Web/Areas/TimeAttendance/Views/AbsenceReport/_List.cshtml
@model List<TimeAttendance.Model.AnalyzedReportListModel>
@{
    Layout = null;

    List<TimeAttendance.Model.AnalyzedReportListModel> entityList = new List<TimeAttendance.Model.AnalyzedReportListModel>();

    entityList = Model;
}

<style>
    .nopadding{
        padding:5px !important;
        width:33% !important;
    }
</style>


@if (entityList == null)
{
    <div class="alert alert-warning w100 pull-right">
        داده ای یافت نشد!
    </div>
}
else
{
    foreach (var user in entityList)
    {
        <div class="panel-group pabel-accordion" id="accordion@(entityList.FindIndex(x => x.UserInformattion == user.UserInformattion))">
            <div class="panel panel-info">
                <a class="accordion-toggle accordion-toggle-styled " data-toggle="collapse" data-parent="#accordion@(entityList.FindIndex(x => x.UserInformattion == user.UserInformattion))" href="#collapse_@(entityList.FindIndex(x => x.UserInformattion == user.UserInformattion))_@(entityList.FindIndex(x => x.UserInformattion == user.UserInformattion))" aria-expanded="false">
                    <div class="panel-heading panel-heading-gray">
                        <h4 class="panel-title">
                            <table class="w100 pull-right" style="position: relative;top: -20px;">
                                <tbody>
                                    <tr>
                                        <td>
                                            @(user.UserGroup)
                                        </td>
                                        <td>
                                            @(user.UserInformattion)
                                        </td>
                                        <td>
                                            @(user.StartDate)
                                        </td>
                                        <td>
                                            @(user.EndDate)
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </h4>
                    </div>
                </a>
                <div id="collapse_@(entityList.FindIndex(x => x.UserInformattion == user.UserInformattion))_@(entityList.FindIndex(x => x.UserInformattion == user.UserInformattion))" class="panel-collapse collapse " style="">
                    <div class="panel-body">
                        <table id="Grid" class="table  table-striped table-condensed table-bordered no-margin smallTable" style="width:100% !important;">
                            <thead>
                                <tr>
                                    <th>ردیف</th>
                                    <th>وضعیت</th>
                                    <th>تاریخ</th>
                                    <th>روز</th>
                                    <th>ترددها</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (user.Reports.Count() <= 0 || Model == null)
                                {
                                    <tr>
                                        <td colspan="5">داده ای یافت نشد !</td>
                                    </tr>
                                }
                                else
                                {
                                    foreach (var item in user.Reports)
                                    {
                                        <tr>
                                            <td>
                                                @(user.Reports.FindIndex(x => x.Id == item.Id) + 1)
                                            </td>
                                            <td>
                                                @switch (item.State)
                                                {
                                                    case wskh.Core.Enumerator.AnalyzedReportState.WaitingForAnalyzing:
                                                        <span class='text-info'>درحل آنالیز</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.Presence:
                                                        <span class='text-success'>حضور</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.Absence_NoTransaction:
                                                        <span class='text-danger'>غیبت</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.Absence_Systemic:
                                                        <span class='text-danger'>غیبت سیستمی</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.FractionTrade:
                                                        <span class='text-warning'>تردد ناقص</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.RestDay:
                                                        <span class='text-dark'>روز استراحت</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.Holiday:
                                                        <span class='text-dark'>تعطیلی</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.Holiday_Presence:
                                                        <span class='text-success'>حضور-روز تعطیل</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.HolidayFraction:
                                                        <span class='text-warning'>ترددناقص-روز تعطیل</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.Holiday_Absence_NoTransaction:
                                                        <span class='text-danger'>غیبت-روز تعطیل</span>
                                                        break;
                                                    case wskh.Core.Enumerator.AnalyzedReportState.Holiday_Absence_Systemic:
                                                        <span class='text-danger'>غیبت سیستمی-روز تعطیل</span>
                                                        break;
                                                    default:
                                                        <span class='text-dark'>-</span>
                                                        break;
                                                }


                                            </td>
                                            <td>
                                                @(item.PersianDate)
                                            </td>
                                            <td>
                                                @(item.PersianDayName)
                                            </td>
                                            <td>
                                                @if (item.AnalyzedReportLogs != null)
                                                {
                                                    <table style="width:100%">
                                                        <tbody>
                                                            @foreach (var log in item.AnalyzedReportLogs)
                                                            {
                                                                <tr>
                                                                    <td class="nopadding">@(wskh.WebEssentials.DateAndTime.DateTimeHelper.ToHourMinute(log.FirstLog.LogTime))</td>
                                                                    <td class="nopadding">@(wskh.WebEssentials.DateAndTime.DateTimeHelper.ToHourMinute(log.SecondLog?.LogTime))</td>
                                                                    <td class="nopadding">@(wskh.WebEssentials.DateAndTime.DateTimeHelper.ToHourMinute(log.Duration))</td>
                                                                </tr>

                                                            }
                                                        </tbody>
                                                    </table>

                                                }
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>



                    </div>
                </div>
            </div>
        </div>
    }
}

wskh.Web/Areas/TimeAttendance/Views/AbsenceReport/_Search.cshtml
@model TimeAttendance.Model.AnalyzedReportModel
@{
    Layout = null;
}

<link href="~/wwwroot/componenets/persiancalendar/js-persian-cal.css" rel="stylesheet" />


@Html.AntiForgeryToken()




<div class="row">
    <div class="form-group pull-right col-md-2">
        @Html.LabelFor(x => x.UserGroupId, new { @class = "pull-right" })
        @Html.DropDownListFor(x => x.UserGroupId, Model.UserGroupList, new { @class = "form-control", onchange = "SelectUsers()" })
        @Html.ValidationMessageFor(x => x.UserGroupId, null, new { @class = "validation" })
    </div>
    <div class="form-group pull-right col-md-2">
        @Html.LabelFor(x => x.UserId, new { @class = "pull-right" })
        <select class="form-control" id="UserId" name="UserId" autocomplete="off">
            @Html.Action("GetDrop", new { usergroupId = 0 })
        </select>

        @Html.ValidationMessageFor(x => x.UserId, null, new { @class = "validation" })
    </div>
    <div class="form-group pull-right col-md-2">
        <label class="pull-right" for="UserGroupId">نوع  گزارش</label>
        <select class="form-control" id="TypeId" name="TypeId">
            <option value="0">
                تمام موارد
            </option>
            <option value="1">
                غیبت
            </option>
            <option value="2">
               غیبت سیستمی
            </option>
        </select>
    </div>
    <div class="form-group pull-right col-md-1">
        @Html.LabelFor(x => x.StartDatePersian, new { @class = "pull-right" })<label class="required">*</label>
        @Html.TextBoxFor(x => x.StartDatePersian, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.StartDatePersian, null, new { @class = "validation" })
    </div>
    <div class="form-group pull-right col-md-1">
        @Html.LabelFor(x => x.EndDatePersian, new { @class = "pull-right" })<label class="required">*</label>
        @Html.TextBoxFor(x => x.EndDatePersian, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.EndDatePersian, null, new { @class = "validation" })
    </div>
    <div class="form-group pull-left col-md-2">
        <button type="button" onclick="Search()" id="submitBTN" class="btn btn-success btn-sm pull-left" style="position: relative;top: 38px;float: left;width:100%">جستجو</button>
    </div>
    <div class="form-group pull-left col-md-2">
        <button type="button" onclick="PrintPDF()" class="btn btn-default btn-sm pull-left" style="position: relative;top: 38px;float: left;width:100%">چاپ <i class="fa fa-copy"></i></button>
    </div>
</div>






<script src="~/wwwroot/componenets/persiancalendar/js-persian-cal.min.js"></script>
<script type="text/javascript">
    var objCal1 = new AMIB.persianCalendar('StartDatePersian');
    var objCal2 = new AMIB.persianCalendar('EndDatePersian');
</script>